datezite/Controllers/ProfilesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using datezite.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;


namespace datezite.Controllers
{

    [Authorize]
    public class ProfilesController : Controller
    {
        private ApplicationDbContext _context;

            
        public ProfilesController()
        {
            _context = new ApplicationDbContext();
        }

        public ApplicationUser GetUserByName(string name)
        {
            var appUser = _context.Users.Single(u => u.UserName == name);

            foreach (var entry in _context.Entries)
            {
                if (entry.RecipientId == appUser.Id)
                {
                    appUser.Inlägg.Add(entry);
                }
            }
            return appUser;
        }

        public ActionResult Update(EditYourProfileViewModel LoggedInUser)
        {            
            var UserToChange = GetUserByName(User.Identity.Name);

            LoggedInUser.CurrentUser.UserName = UserToChange.UserName;

            var user = _context.Users.SingleOrDefault(u => u.UserName == UserToChange.UserName);

            user.Förnamn = LoggedInUser.CurrentUser.Förnamn.Substring(0,1).ToUpper() + LoggedInUser.CurrentUser.Förnamn.Substring(1).ToLower();
            user.Efternamn = LoggedInUser.CurrentUser.Efternamn.Substring(0, 1).ToUpper() + LoggedInUser.CurrentUser.Efternamn.Substring(1).ToLower();
            user.Sysselsättning = LoggedInUser.CurrentUser.Sysselsättning;
            user.Kön = LoggedInUser.CurrentUser.Kön;
            user.Ålder = LoggedInUser.CurrentUser.Ålder;
            
            _context.SaveChanges();
            return RedirectToAction("YourProfile");
        }

        public ActionResult ChangeProfilePicture([Bind(Exclude = "UserPhoto")]ApplicationUser LoggedInUser) {

            var UserToChange = GetUserByName(User.Identity.Name);
            LoggedInUser.UserName = UserToChange.UserName;
            var user = _context.Users.SingleOrDefault(u => u.UserName == UserToChange.UserName);

            byte[] imageData = null;
            if (Request.Files.Count > 0)
            {
                HttpPostedFileBase poImgFile = Request.Files["UserPhoto"];

                using (var binary = new BinaryReader(poImgFile.InputStream))
                {
                    imageData = binary.ReadBytes(poImgFile.ContentLength);
                }
            }

            user.UserPhoto = imageData;

            _context.SaveChanges();
            return RedirectToAction("YourProfile");
        }

        public ActionResult EditYourProfile(EditYourProfileViewModel model)
        {

            var user = GetUserByName(User.Identity.Name);
            var intressen = _context.Intressen.ToList();
            model.CurrentUser = new ApplicationUser();

            model.CurrentUser.Ålder = user.Ålder;
            model.CurrentUser.Förnamn = user.Förnamn;
            model.CurrentUser.Efternamn = user.Efternamn;
            model.CurrentUser.Sysselsättning = user.Sysselsättning;
            model.CurrentUser.Kön = user.Kön;

            model.Requests = new List<ApplicationUser>();
            var allFriendRequests = _context.Friendrequests.ToList();

            foreach (var u in allFriendRequests)
            {
                if (model.CurrentUser.Id == u.FriendId)
                {
                    model.Requests.Add(GetOtherUser(u.UserId));
                }
            }
            return View(model);
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ActionResult MyMatches(MyMatchesViewModel model)
        {
            model.Requests = new List<ApplicationUser>();
            var allFriendRequests = _context.Friendrequests.ToList();
            var user = GetUserByName(User.Identity.Name);

            foreach (var u in allFriendRequests)
            {
                if (user.Id == u.FriendId)
                {
                    model.Requests.Add(GetOtherUser(u.UserId));
                }
            }

            return View(model);
        }

        public ActionResult PotentialMatches(PotentialMatchesViewModel model)
        {
            model.Requests = new List<ApplicationUser>();
            var allFriendRequests = _context.Friendrequests.ToList();
            var user = GetUserByName(User.Identity.Name);

            foreach (var u in allFriendRequests)
            {
                if (user.Id == u.FriendId)
                {
                    model.Requests.Add(GetOtherUser(u.UserId));
                }
            }

            return View(model);
        }

        public ActionResult OtherProfile(OtherProfileViewModel model, String Id)
        {
            var otherUser = GetOtherUser(Id);
            model.CurrentUser = new ApplicationUser();

            model.CurrentUser.UserName = otherUser.UserName;
            var you = GetUserByName(User.Identity.Name);
            var user = _context.Users.Single(u => u.UserName == model.CurrentUser.UserName);

            model.CurrentUser.Id = user.Id;
            model.CurrentUser.Förnamn = user.Förnamn;
            model.CurrentUser.Efternamn = user.Efternamn;
            model.CurrentUser.Ålder = user.Ålder;
            model.CurrentUser.Kön = user.Kön;
            model.CurrentUser.Sysselsättning = user.Sysselsättning;
            model.CurrentUser.UserName = user.UserName;
            foreach(var entry in _context.Entries)
            {
                if (model.CurrentUser.Id == entry.RecipientId)
                {
                    model.CurrentUser.Inlägg.Add(entry);
                }
            }

            model.Requests = new List<ApplicationUser>();
            var allFriendRequests = _context.Friendrequests.ToList();

            foreach (var u in allFriendRequests)
            {
                if (you.Id == u.FriendId)
                {
                    model.Requests.Add(GetOtherUser(u.UserId));
                }
            }



            return View(model);
        }

        public ActionResult YourProfile(ProfileViewModel model)
        {
            var user = GetUserByName(User.Identity.Name);
            var allFriends = _context.Friends.ToList();
            model.CurrentUser = user;
            model.CurrentUser.Id = user.Id;
            model.CurrentUser.Förnamn = user.Förnamn;
            model.CurrentUser.Efternamn = user.Efternamn;
            model.CurrentUser.Ålder = user.Ålder;
            model.CurrentUser.Kön = user.Kön;
            model.CurrentUser.Id = user.Id;
            model.CurrentUser.Sysselsättning = user.Sysselsättning;
            model.CurrentUser.UserPhoto = user.UserPhoto;
            model.CurrentUser.Inlägg = user.Inlägg;
            model.Friends = new List<ApplicationUser>();

            foreach (var f in allFriends)
            {
                if (f.UserId == user.Id)
                {
                    model.Friends.Add(GetOtherUser(f.FriendId));
                }
                if (f.FriendId == user.Id)
                {
                    model.Friends.Add(GetOtherUser(f.UserId));
                }
            }

            model.WallEntrys = new List<Entry>();
            
            foreach (var entry in _context.Entries)
            {
                if (entry.RecipientId == user.Id)
                {
                    model.WallEntrys.Add(entry);
                }
            }

            model.Requests = new List<ApplicationUser>();
            var allFriendRequests = _context.Friendrequests.ToList();

            foreach (var u in allFriendRequests)
            {
                if (user.Id == u.FriendId)
                {
                    model.Requests.Add(GetOtherUser(u.UserId));
                }
            }


            return View(model);
        }



        public FileContentResult UserPhotos()
        {
                string userId = User.Identity.GetUserId();
                var LoggedInUser = GetUserByName(User.Identity.Name);
                if (LoggedInUser.UserPhoto.Length == 0)
                {
                    string fileName = HttpContext.Server.MapPath(@"~/Images/noImg.jpg");
                    byte[] imageData = null;
                    FileInfo fileInfo = new FileInfo(fileName);
                    long imageFileLength = fileInfo.Length;
                    FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
                    BinaryReader br = new BinaryReader(fs);
                    imageData = br.ReadBytes((int)imageFileLength);

                    return File(imageData, "image/png");
                }

                var bdUsers = HttpContext.GetOwinContext().Get<ApplicationDbContext>();
                var userImage = bdUsers.Users.Where(u => u.Id == userId).FirstOrDefault();

                return new FileContentResult(userImage.UserPhoto, "image/jpeg");
        }

        public FileContentResult OtherUsersPhoto(string Id)
        {  
                string userId = Id;
                var OtherUser = GetOtherUser(userId);
                if (OtherUser.UserPhoto == null || OtherUser.UserPhoto.Length == 0)
                {
                    string fileName = HttpContext.Server.MapPath(@"~/Images/noImg.jpg");
                    byte[] imageData = null;
                    FileInfo fileInfo = new FileInfo(fileName);
                    long imageFileLength = fileInfo.Length;
                    FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
                    BinaryReader br = new BinaryReader(fs);
                    imageData = br.ReadBytes((int)imageFileLength);

                    return File(imageData, "image/png");
                }


                var bdUsers = HttpContext.GetOwinContext().Get<ApplicationDbContext>();

datezite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body style="padding-top:unset; padding-bottom:unset">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="/Home/Index">Hem</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/Account/Register">Registrera dig <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item ">
                    <a class="nav-link" href="/Account/Login">Logga in</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - LTP Dating</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

datezite/Views/Shared/_NavBarSignedIn.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="/Home/Index"> Hem </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item ">
                <a class="nav-link" href="@Url.Action("PotentialMatches", "Profiles" )">Potentiella Matchningar </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="@Url.Action("MyMatches", "Profiles" )">Mina matchningar</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="@Url.Action("YourProfile", "Profiles" )">Min Profil</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="@Url.Action("LogOff", "Account")">Logga ut</a>
            </li>
        </ul>
        <div id="noReqs">
            <a  href="@Url.Action("FriendRequests", "Profiles")"><img src="~/Images/user_white_klippt.png" style="width:30px; height:30px; display:block"/></a>
        </div>
        <div id="friendReqs">
            <a  href="@Url.Action("FriendRequests", "Profiles")"><img src="~/Images/user_white_dot.png" style="width:32px; height:35px; display:block"/></a>
        </div>
        
        
        @using (Html.BeginForm("SearchView", "Profiles", new { @class = "form-inline my-2 my-lg-0" }))
        {
            <p style="padding-left: 20px">
                Sök: @Html.TextBox("searchName")
                <input type="submit" value="search" />
            </p>
        }
    </div>
</nav>
<script src="~/Scripts/jquery-3.3.1.js"></script>
<script>
    $(document).ready(function () {
    if (@Model.Requests.Count != 0) {
    $('#noReqs').hide();
    $('#friendReqs').show();
} else {
    $('#friendReqs').hide();
    $('#noReqs').show();
}
    });


</script>

datezite/Views/Shared/_SignedInLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


</head>
<body style="padding-top:unset; padding-bottom:unset">

@Html.Partial("_NavBarSignedIn");
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - LTP Dating</p>
        </footer>
    </div>
    <script>
    </script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>